import React from "react";
import Styles from "../EssayTopics/index.module.scss"
import Image from "../Assets/graphic.jpg";
import CommanBanner from "../component/CommanBanner";
import Container from "../component/Container";
import CommanHeading from "../component/CommanHeading";
import Item from "../component/Item";
import CourseCrousel from "../CourceDetails/CourseCrousel";


const GSPaper_4 = () => {
  return (
    <>
      <CommanBanner section="GENERAL STUDIES PAPER 4 - UPSC CIVIL SERVICES IAS EXAM 2021 QUESTION PAPER" />
      <div className={Styles.courcesPage}>
        <Container>
          <div className={Styles.courcesPage__rowflex}>
            <div className={Styles.courcesPage__rowflex__couresDetails}>
              <div className={Styles.courcesPage__rowflex__couresDetails__inner}>
                <h2>GENERAL STUDIES PAPER 4 - UPSC CIVIL SERVICES IAS EXAM 2021 QUESTION PAPER</h2>
                <img src={Image} alt="image" />

                <CommanHeading
                  heading="GENERAL STUDIES PAPER 4 - UPSC CIVIL SERVICES IAS EXAM 2021 QUESTION PAPER"
                />
                <Item para="1. (a) Identify five ethical traits on which one can plot the performance of a civil servant. Justify their inclusion in the matrix. (Answer in 150 words) " />
                <Item para="(b) Identify ten essential values that are needed to be an effective public servant. Describe the /ways and means to prevent non-ethical behaviour in the pubic servants. (Answer in 150 words) " />
                <Item para="2. (a) Impact of digital technology as reliable source of input for rational decision making is debatable issue. Critically evaluate with suitable example. (Answer in 150 words) " />
                <Item para="(b) Besides domain knowledge, a public official needs innovativeness and creativity of a high order as well, while resolving ethical dilemmas. Discuss with suitable example. (Answer in 150 words)" />
                <CommanHeading
                  heading="What does each of the following quotations mean to you?"
                />
                <Item para="(a) Every work has got to pass through hundreds of difficulties before succeeding. Those that persevere will see the light, sooner or later.-Swami Vivekananda (Answer in 150 words) " />
                <Item para="(b) We can never obtain peace in the outer world until and unless we obtain peace within ourselves.” – Dalai Lama (Answer in 150 words)" />
                <Item para="(c) Life doesn’t make any sense without interdependence. We need each other, and the sooner we learn that, it is better for us all.” -Erik Erikson word (Answer in 150 word) " />
                <Item para="4. (a) Attitude is an important component that goes as input in the elopement of human How to build a suitable needed for a public servant? (Answer in 150 words " />
                <Item para="(b) In case of crisis of conscience does emotional intelligence help to overcome the same without compromising the ethical or moral stand that you are likely to follow? Critically examine. (Answer in 150 words)" />
                <Item para="5. (a)Refugees should not be turned back to the country where they would face persecution or human right violation.” Examine the statement with reference to ethical dimension being violated by the nation claiming to be democratic with open society. (Answer in 150 words) " />
                <Item para="(b) Should impartial and being non-partisan be considered as indispensable qualities to make a successful civil servant? Discuss with illustrations. (Answer in 150 words) " />
                <Item para="6. (a) An independent and empowered social audit mechanism is an absolute must in every sphere of public service, including judiciary, to ensure performance, accountability and ethical conduct. Elaborate. (Answer in 150 words) " />
                <Item para="(b) “Integrity is a value that empowers the human being.” Justify with suitable illustration. (Answer in 150 words) " />
                <Item para="7. Sunil is a young civil servant and has a reputation for his competence, integrity, dedication and relentness pursuit of difficult and onerous jobs. Considering his profile, he was picked up by his bosses to handle a very challenging and sensitive assignment. He was posted in a tribal dominated district notorious for illegal sand mining. Excavating sand from river belt and transporting through trucks and selling them in black market was rampant. This illegal sand mining mafia was operating with the support of local functionaries and tribal musclemen who in turn were bribing selected poor tribals and had kept the tribals under fear and intimidation. Sunil being a sharp and energetic officer immediately grasped the ground realities and the modus operandi followed by the mafia through their devious and dubious mechanism. On making inquiries, he gathered that some of their own office employees are in hand and glove with them and have developed close unholy nexus. Sunil initiated stringent action against them and started conducting raids on their illegal operations of movement of trucks filled with sand. The mafia got rattled as not many officers in the past had taken such steps against the mafia. Some of the office employees who were allegedly close to mafia informed them that the officer is determined to clean up the mafia’s illegal sand mining operations in that the district and may cause them irrepairable damage. The mafia turned hostile and launched counter-offensive. The tribal musclemen and mafia srted threatening him with dire consequences. His family (wife and old mother) were stalked and were under virtual surveillance and thus causing mental torture, agony and stress to all of them. The matter assumed serious proportions when a muscleman came to his office and threatened him to stop raids, etc., otherwise, his fate will not be different than some of his predecessors (ten years back one officer was killed by the mafia). Identify the different options available to Sunil in attending to this situation. Critically evaluate each of the options listed by you. Which of the above, do you think, would be the most appropriate for Sunil to adopt and why? (Answer in 250 words)" />
                <Item para="8. You are Vice Principal of a degree college in one of the middle – class towns. Principal has recently retired and management is looking for his replacement. There are also feelers that the management may promote you as Principal. In the meantime, during annual examination the flying squad came from the university caught two students red-hande3d involving in unfair means. A senior lecturer of the college was personally helping these student in this act. This senior lecturer also happens to be close to the management. One of the students was son of a local politician who was responsible in getting college affiliated to the present reputed university. The second student was son of a local businessman who has donated maximum funds for running of the college. You immealately informed the management regarding this unfortunate incident. The management told you to resolve the issue with flying squad at any cost. They further said that such incident will not only tarnish the image of the college but also the politician and businessman are very important personalities for the functioning of the college. You were also given hint that your further promotion to Principal depends on your capability in resolving this issue with flying squad. In the meantime, you were intimated by your administrative officer that certain members of the student union are protesting outside the college gate against the senior lecturer and the students involved in this incident and demanding strict action against defaulters. Discuss the ethical issues involved in the case. Critically examine the options available with you as Vice Principal. What option will you adopt and why? (Answer in 250 words)" />
                <Item para="9. An elevated corridor is being constructed to reduce traffic congestion in the capital of a particular state. You have been selected as project manager of this prestigious project on your professional competence and experience. The deadline is to complete the project in next two years by 20 June, 2021, since this project is to be inaugurated by the Chief Minister before the elections are announced in the second week of July 2021. While carrying out the surprise inspection by inspecting team, a minor crack was noticed in one of the piers of the elevated corridor possibly due to poor material used. You immediately informed the chief engineer and stopped further work. It was assessed by you that minimum three piers of the elevated corridor have to be demolished demolished and reconstructed. But this process will delay the project minimum by four to six months. But the chief engineer overruled the observation of inspecting team on the ground that it was a minor crack which will not in any way impact the strength and durability of the bridge. He ordered you to overlook the observation of inspecting team and continue working with same speed and tempo. He informed you that the minister does not want any delay as he wants the chief Minister to inaugurate the elevated corridor before the elections are declared. Also informed you that the contractor is far relative of the minister and he wants him to finish the project. He also gave you hint that your further promotion as additional chief engineer is under consideration with the ministry. However, you strongly felt that the minor crack in the pier of the elevated corridor will adversely affect the health and life of the bridge and therefore it will be very dangerous not to repair the elevated corridor. Under the given conditions, what are the options available to you as a project manager? What are the ethical dilemmas being faced by the project manager? What are the professional challenges likely to be faced by the project manager and his response to overcome such challenges? What can be the consequences of overlooking the observation raised by the inspecting team? (Answer in 250 words)" />
                <Item para="10. The coronavirus disease (CoVID-19) pandemic has quickly spread to various countries. As on May 8th, 2020, in India 56342 positive cases of corona had been reported. India with a population of more than 1-35 billion had difficulty in controlling the transmission of coronavirus among its population. Multiple strategies became necessary to handle this outbreak. The Ministry of Health and Family Welfare of India raised awareness about this outbreak and to take all necessary actions to control the spread of COVID-19. Indian Government implemented a 55-day lockdown throughout the country to reduce the transmission of the virus. Schools and colleges had shifted to alternative mode of teaching- learning-evaluation and certification. Online mode became popular during these days. India was not prepared fora sudden onslaught of such a crisis due to limited infrastructure in terms of human resource, money and other facilities needed for taking care of this situation. This disease did not spare anybody irrespective of caste, creed, religion on the one hand and have and have not’ on the other. Deficiencies in hospital beds, oxygen cylinders, ambulances, hospital staff and crematorium were the most crucial aspects You are a hospital administrator in a public hospital at the time when coronavirus had attacked large number of people and patients were pouring into hospital day in and day out. What are your criteria and justification for putting your clinical and non-clinical staff to attend to the patients knowing fully well that it is highly infectious disease and resources and infrastructure are limited? If yours is a private hospital, whether your justification and decision would remain same as that of a public hospital? (Answer in 250 words)" />
                <Item para="11. A Reputed food product company based in India developed a food product for international market and started exporting the same after getting necessary approvals. The company announced this achievement and also indicated that soon the product will be made available for the domestic consumers with almost sane quality and health benefits. Accordingly, the company got its product approved by the domestic competent authority and launched the product in Indian market. The company could increase its market share over a period of time and earned substantial profit both domestically and internationally. However, the random sample test conducted by inspecting team found the product being sold domestically in variance with the approval obtained from the competent authority. On further investigation, it was also discovered that the food company was not only selling products which were not meeting the health standard of the country but also selling the rejected export products in the domestic market. This episode adversely affected the reputation and profitability of the food company. What action do you visualize should be taken by the competent authority against the food company for violating the laid down domestic food standard and selling rejected export products in domestic market? What course of action is available with the food company to resolve the crisis and bring back its lost reputation? Examine the ethical dilemma involved in the case. (Answer in 250 words)" />
                <Item para="12. Pawan is working as an officer in the State Government for the last ten years. As a part of routine transfer, he was posted to another department. He joined in a new office along with five other colleagues. The head of the office was a senior officer conversant with the functioning of the office. As a part of general inquiry, Pawan gathered that his senior officer carries the reputation of being difficult and insensitive person having his own disturbed family life. Initially, all seem to go well. However, after some time Pawan felt that the senior officer was belittling him and at times unreasonable. Whatever suggestions given or views expressed by Pawan in the meetings were summarily rejected and the senior officer would express displeasure in the presence of others. It became a pattern of boss’s style of functioning to show him in bad light highlighting his shortcomings and humiliating publically. It became apparent that though there are no serious work-related problems/shortcomings, the senior officer was always on one pretext or the other and would scold and shout at him. The continuous harassment and public criticism of Pawan resulted in loss of confidence, self-esteem and equanimity. Pawan realized that his relations with his senior officer are becoming more toxic and due to this, he felt perpetually tensed, anxious and stressed. His mind was occupied with negativity and caused him mental torture, anguish and agony. Eventually, it badly affected his personal and family life. He was no longer joyous, happy and contented even t home. Rather without any reason he would loose his temper with his wife and other family members. The family environment was no longer pleasant and congenial. His wife who was always supportive to him also became a victim of his negativity and hostile behaviour. Due to harassment and humiliation suffering by him in the office, comfort and happiness virtually vanished from his life. Thus it damaged his physical and mental health. What are the options available with Pawan to cope with the situation? What approach Pawan should adopt for bringing peace, tranquillity and congenial environment in the office 
                and home? As an outsider, what are your Suggestions for both boss and subordinate to overcome this situation and for improving the work performance, mental and emotional hygiene? In the above scenario, what type of training would you suggest for at various levels in the government offices? (Answer in 250 words)" />

                <h3>&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;Download UPSC CIVIL SERVICES IAS EXAM 2021 GENERAL STUDIES PAPER 4</h3>
              </div>

            </div>
          </div>
          <div className={Styles.courcesPage__rowflex__couresDetails__crousalArea}>
            <h3>Related Courses</h3>
          </div>
          <CourseCrousel />
        </Container>
      </div>
    </>
  );
};

export default GSPaper_4;
